// Backlog item `harness-goal-primitives`, then settled by `loop-dmi-conflict` (2026-07-20):
// plugin/commands/runner.md's Scheduling section documents the runner's standing cadence. `/loop`
// and `/goal` are Claude-only harness primitives (Codex has no equivalent), so
// scripts/build-codex.mjs must strip them from the generated Codex runner command entirely --
// proven here against the BUILT Codex plugin tree (test-support/codex-helpers.js's
// selectedPluginRoot, regenerated by the `pretest` hook before this file runs).
//
// The `/loop`x`disable-model-invocation` question is now settled from primary docs, not hedged:
// as of Claude Code v2.1.196 a scheduled/`/loop` fire does not execute a
// `disable-model-invocation: true` command (it reaches Claude as plain text), so
// `/loop /muster:runner` will not re-fire runner.md. The Scheduling section states that definitive
// fact (dated, cited) and points a native self-continuing loop at `/goal`; Routine/cron stay the
// verified-safe standing-cadence default. These assertions pin the definitive wording, replacing
// the earlier "self-pacing" / "verify before relying on it" hedge assertions.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { selectedPluginRoot } from "../test-support/codex-helpers.js";

const root = new URL("../", import.meta.url);
const read = (p) => readFile(new URL(p, root), "utf8");

test("plugin/commands/runner.md documents the runner's standing cadence with the settled /loop x dmi fact", async () => {
  const text = await read("plugin/commands/runner.md");
  // Routine/cron is the verified-safe standing-cadence default.
  assert.match(text, /Claude Code Routine/, "the Routine/cron alternative must remain documented");
  assert.match(text, /claude -p "\/muster:runner issues:agent:todo"/, "the cron example must remain documented");
  // Safety inventory paragraph applies unchanged (same load-bearing terms as before this item).
  for (const term of ["pr-only", "2-failure retry cap", "claim lock"]) {
    assert.ok(text.includes(term), `Scheduling section must still name ${term}`);
  }
  // The exact /loop invocation form is still named -- now as the mechanism that is documented-inert.
  assert.match(text, /\/loop \/muster:runner <source>/, "must name the exact /loop invocation form");
  // Settled definitively from primary docs, NOT hedged: runner.md carries disable-model-invocation:true,
  // and as of v2.1.196 a scheduled/`/loop` fire does not execute such a command -- it reaches Claude
  // as plain text -- so /loop does not re-fire this command.
  assert.match(text, /disable-model-invocation/, "must name the disable-model-invocation interaction");
  assert.match(text, /v2\.1\.196/, "must cite the v2.1.196 documented behavior");
  assert.match(text, /plain text/, "must state the fire reaches Claude as plain text instead of executing");
  // The hedge is gone: no "likely blocked" / "verify before relying on it" / live-cycle instruction.
  assert.doesNotMatch(text, /likely blocked|verify before relying|run one live cycle|Unverified interaction/i,
    "the hedge must be replaced by the definitive documented fact");
  // Native self-continuing alternative points at /goal (condition-based, distinct from /loop).
  assert.match(text, /\/goal/, "must point to /goal as the native condition-based self-continuing alternative");
});

test("generated Codex runner command does NOT carry the Claude-only /loop or /goal bindings", async () => {
  const text = await readFile(join(selectedPluginRoot, "commands", "runner.md"), "utf8");
  assert.doesNotMatch(text, /\/loop\b/, "Codex has no /loop primitive -- must not leak into the generated command");
  assert.doesNotMatch(text, /\$loop\b/, "must not leak as a translated Codex mode-name form either");
  assert.doesNotMatch(text, /\/goal\b/, "Codex has no /goal primitive -- must not leak into the generated command");
  assert.doesNotMatch(text, /self-pacing/i, "Codex build must not carry the self-pacing framing either");
  // The cron/automation alternative must still be present, Codex-translated.
  assert.match(text, /Codex automation/);
  assert.match(text, /codex exec "\$muster-runner issues:agent:todo"/);
});
