// Backlog item `harness-goal-primitives`, Claude lane: plugin/commands/runner.md's Scheduling
// section documents Claude Code's native `/loop` binding as a first-class alternative to firing
// `/muster:runner` from a Claude Code Routine/cron. `/loop` is a Claude-only harness primitive
// (Codex has no equivalent), so scripts/build-codex.mjs must strip it from the generated Codex
// runner command entirely -- proven here against the BUILT Codex plugin tree
// (test-support/codex-helpers.js's selectedPluginRoot, regenerated by the `pretest` hook before
// this file runs).
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { selectedPluginRoot } from "../test-support/codex-helpers.js";

const root = new URL("../", import.meta.url);
const read = (p) => readFile(new URL(p, root), "utf8");

test("plugin/commands/runner.md documents the native /loop binding as a first-class scheduling alternative", async () => {
  const text = await read("plugin/commands/runner.md");
  assert.match(text, /\/loop \/muster:runner <source>/, "must document the exact /loop invocation form");
  assert.match(text, /self-pacing/i, "must name the self-pacing recurrence mechanism");
  assert.match(text, /Claude Code Routine/, "the Routine/cron alternative must remain documented");
  assert.match(text, /claude -p "\/muster:runner issues:agent:todo"/, "the cron example must remain documented");
  // Safety inventory paragraph applies unchanged (same load-bearing terms as before this item).
  for (const term of ["pr-only", "2-failure retry cap", "claim lock"]) {
    assert.ok(text.includes(term), `Scheduling section must still name ${term}`);
  }
  // Review-gate finding: runner.md carries disable-model-invocation:true, and Claude Code's own
  // scheduled-fire docs don't resolve whether that blocks /loop's own re-fires of an explicit
  // slash-command prompt -- the Scheduling section must caveat this honestly rather than assert
  // unconditional certainty (the same "verify before wiring" bar the Codex goals record holds).
  assert.match(text, /disable-model-invocation/, "must name the disable-model-invocation interaction");
  assert.match(text, /confirm|verif/i, "must instruct confirming/verifying the behavior before relying on it");
});

test("generated Codex runner command does NOT carry the Claude-only /loop binding", async () => {
  const text = await readFile(join(selectedPluginRoot, "commands", "runner.md"), "utf8");
  assert.doesNotMatch(text, /\/loop\b/, "Codex has no /loop primitive -- must not leak into the generated command");
  assert.doesNotMatch(text, /\$loop\b/, "must not leak as a translated Codex mode-name form either");
  assert.doesNotMatch(text, /self-pacing/i, "Codex build must not carry the self-pacing framing either");
  // The cron/automation alternative must still be present, Codex-translated.
  assert.match(text, /Codex automation/);
  assert.match(text, /codex exec "\$muster-runner issues:agent:todo"/);
});
