import { test } from "node:test";
import assert from "node:assert/strict";
import { validateVendorManifest, toBuiltin, generateNotice, runVendor } from "../src/vendor.js";
import { mkdtemp, mkdir, writeFile, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

test("validateVendorManifest accepts a well-formed manifest", () => {
  const doc = { sources: [
    { id: "superpowers", kind: "local", repo: "obra/superpowers", license: "MIT",
      items: [{ from: "brainstorming/SKILL.md", id: "sp-brainstorm", roles: ["brainstorm"] }] }
  ]};
  assert.deepEqual(validateVendorManifest(doc), { ok: true, errors: [] });
});

test("validateVendorManifest rejects missing license / bad kind / itemless", () => {
  const doc = { sources: [{ id: "x", kind: "ftp", items: "no" }] };
  const r = validateVendorManifest(doc);
  assert.equal(r.ok, false);
  assert.ok(r.errors.some(e => /license/.test(e)));
  assert.ok(r.errors.some(e => /kind/.test(e)));
  assert.ok(r.errors.some(e => /items/.test(e)));
});

test("validateVendorManifest rejects item missing from/id/roles", () => {
  const doc = { sources: [{ id: "s", kind: "local", license: "MIT", items: [{ id: "only" }] }] };
  const r = validateVendorManifest(doc);
  assert.equal(r.ok, false);
  assert.ok(r.errors.some(e => /from/.test(e)));
  assert.ok(r.errors.some(e => /roles/.test(e)));
});

const src = `---\nname: brainstorming\ndescription: Explore before building\n---\n\n# Brainstorming\nDo the thing.\n`;
const item = { from: "brainstorming/SKILL.md", id: "sp-brainstorm", roles: ["brainstorm"] };
const source = { repo: "obra/superpowers", license: "MIT" };

test("toBuiltin merges provenance frontmatter, preserves body", () => {
  const r = toBuiltin(src, item, source);
  assert.equal(r.path, "plugin/builtins/sp-brainstorm/SKILL.md");
  assert.match(r.content, /muster_builtin: true/);
  assert.match(r.content, /adapted_from: obra\/superpowers brainstorming\/SKILL.md/);
  assert.match(r.content, /license: MIT/);
  assert.match(r.content, /name: brainstorming/);
  assert.match(r.content, /Do the thing\./);
});

test("toBuiltin emits a valid catalog builtin entry", () => {
  const r = toBuiltin(src, item, source);
  assert.deepEqual(r.catalogEntry, {
    id: "sp-brainstorm", kind: "builtin", roles: ["brainstorm"], rank: 50,
    provenance: { adapted_from: "obra/superpowers brainstorming/SKILL.md", license: "MIT" }
  });
});

test("toBuiltin derives name/description when source has no frontmatter", () => {
  const r = toBuiltin("# Bare\nbody", { from: "x.md", id: "wsh-x", roles: ["implement"] }, source);
  assert.match(r.content, /name: wsh-x/);
  assert.match(r.content, /body/);
});

test("toBuiltin is idempotent", () => {
  assert.equal(toBuiltin(src, item, source).content, toBuiltin(src, item, source).content);
});

test("toBuiltin keeps adapted_from on one line (no yaml wrapping)", () => {
  const longItem = { from: "plugins/some-very-long-marketplace-path/agents/extremely-long-agent-name.md", id: "wsh-x", roles: ["implement"] };
  const r = toBuiltin("# x\nbody", longItem, { repo: "wshobson/agents", license: "MIT" });
  const line = r.content.split("\n").find(l => l.startsWith("adapted_from:"));
  assert.ok(line.includes("extremely-long-agent-name.md"), "adapted_from must be on a single unwrapped line");
});

test("generateNotice lists each source repo + license once", () => {
  const entries = [
    { provenance: { adapted_from: "obra/superpowers a/SKILL.md", license: "MIT" } },
    { provenance: { adapted_from: "obra/superpowers b/SKILL.md", license: "MIT" } },
    { provenance: { adapted_from: "wshobson/agents x.md", license: "MIT" } }
  ];
  const n = generateNotice(entries);
  assert.match(n, /obra\/superpowers \(MIT\)/);
  assert.match(n, /wshobson\/agents \(MIT\)/);
  assert.equal((n.match(/obra\/superpowers/g) || []).length, 1);
});

test("generateNotice leads with the do-not-edit banner", () => {
  const n = generateNotice([{ provenance: { adapted_from: "obra/superpowers a/SKILL.md", license: "MIT" } }]);
  assert.match(n, /^GENERATED by `muster vendor` from vendor\/manifest\.yaml — do not edit/);
});

// --- runVendor: data-loss guards + banner -------------------------------------
// runVendor only fetches a local source's root for id "superpowers", reading from
// <home>/.claude/plugins/cache/claude-plugins-official/superpowers/<ver>/skills.
// We fabricate that tree so items vendor without a real git clone; any other local
// source id yields root:null, exercising the fetch-failure/empty path.

const SP_BASE = ".claude/plugins/cache/claude-plugins-official/superpowers";

// Seed a fake superpowers skills cache under `home`; `files` maps a relative path
// (the item's `from`) to its source text. Returns nothing.
async function seedSuperpowers(home, files) {
  const skills = join(home, SP_BASE, "v1.0.0", "skills");
  for (const [rel, text] of Object.entries(files)) {
    const abs = join(skills, rel);
    await mkdir(join(abs, ".."), { recursive: true });
    await writeFile(abs, text);
  }
}

async function tmpDirs() {
  const home = await mkdtemp(join(tmpdir(), "muster-vh-"));
  const repoRoot = await mkdtemp(join(tmpdir(), "muster-vr-"));
  return { home, repoRoot };
}

test("runVendor: all sources empty -> count 0, refuse-to-overwrite warning, artifacts untouched", async (t) => {
  const { home, repoRoot } = await tmpDirs();
  t.after(() => Promise.all([rm(home, { recursive: true, force: true }), rm(repoRoot, { recursive: true, force: true })]));

  // Pre-seed existing generated artifacts that must NOT be clobbered.
  await mkdir(join(repoRoot, "catalog"), { recursive: true });
  const sentinel = "- id: pre-existing\n";
  await writeFile(join(repoRoot, "catalog/builtins.generated.yaml"), sentinel);
  await writeFile(join(repoRoot, "catalog/agents.generated.yaml"), sentinel);
  await writeFile(join(repoRoot, "NOTICE"), "PRE-EXISTING NOTICE\n");

  // A local source whose id != superpowers always yields root:null.
  const manifest = { sources: [
    { id: "nope", kind: "local", repo: "x/y", license: "MIT",
      items: [{ from: "a/SKILL.md", id: "a", roles: ["brainstorm"] }] }
  ]};
  const res = await runVendor({ home, repoRoot, manifest });

  assert.equal(res.count, 0);
  assert.ok(res.warnings.some(w => /refusing to overwrite/.test(w)), "expected refuse-to-overwrite warning");
  assert.ok(res.warnings.some(w => /could not fetch/.test(w)), "expected fetch-failure warning");
  // Artifacts unchanged.
  assert.equal(await readFile(join(repoRoot, "catalog/builtins.generated.yaml"), "utf8"), sentinel);
  assert.equal(await readFile(join(repoRoot, "catalog/agents.generated.yaml"), "utf8"), sentinel);
  assert.equal(await readFile(join(repoRoot, "NOTICE"), "utf8"), "PRE-EXISTING NOTICE\n");
});

test("runVendor: agent-only vendor does not rewrite builtins.generated.yaml", async (t) => {
  const { home, repoRoot } = await tmpDirs();
  t.after(() => Promise.all([rm(home, { recursive: true, force: true }), rm(repoRoot, { recursive: true, force: true })]));

  await seedSuperpowers(home, { "ag/AGENT.md": "---\nname: rev\n---\n\nReview body.\n" });
  await mkdir(join(repoRoot, "catalog"), { recursive: true });
  const builtinSentinel = "- id: keep-me\n";
  await writeFile(join(repoRoot, "catalog/builtins.generated.yaml"), builtinSentinel);

  const manifest = { sources: [
    { id: "superpowers", kind: "local", repo: "obra/superpowers", license: "MIT",
      items: [{ from: "ag/AGENT.md", id: "sp-rev", roles: ["architecture-review"], as: "agent" }] }
  ]};
  const res = await runVendor({ home, repoRoot, manifest });

  assert.equal(res.count, 1);
  assert.equal(res.agents, 1);
  assert.equal(res.builtins, 0);
  // builtins catalog untouched (no builtin entries produced).
  assert.equal(await readFile(join(repoRoot, "catalog/builtins.generated.yaml"), "utf8"), builtinSentinel);
  // agents catalog written with the do-not-edit banner.
  const agents = await readFile(join(repoRoot, "catalog/agents.generated.yaml"), "utf8");
  assert.match(agents, /^# GENERATED by `muster vendor` from vendor\/manifest\.yaml — do not edit\n/);
  assert.match(agents, /id: sp-rev/);
});

test("runVendor: builtin-only vendor does not rewrite agents.generated.yaml", async (t) => {
  const { home, repoRoot } = await tmpDirs();
  t.after(() => Promise.all([rm(home, { recursive: true, force: true }), rm(repoRoot, { recursive: true, force: true })]));

  await seedSuperpowers(home, { "bs/SKILL.md": "---\nname: brainstorm\n---\n\nBrainstorm body.\n" });
  await mkdir(join(repoRoot, "catalog"), { recursive: true });
  const agentSentinel = "- id: keep-agent\n";
  await writeFile(join(repoRoot, "catalog/agents.generated.yaml"), agentSentinel);

  const manifest = { sources: [
    { id: "superpowers", kind: "local", repo: "obra/superpowers", license: "MIT",
      items: [{ from: "bs/SKILL.md", id: "sp-bs", roles: ["brainstorm"] }] }
  ]};
  const res = await runVendor({ home, repoRoot, manifest });

  assert.equal(res.builtins, 1);
  assert.equal(res.agents, 0);
  assert.equal(await readFile(join(repoRoot, "catalog/agents.generated.yaml"), "utf8"), agentSentinel);
  const builtins = await readFile(join(repoRoot, "catalog/builtins.generated.yaml"), "utf8");
  assert.match(builtins, /^# GENERATED by `muster vendor` from vendor\/manifest\.yaml — do not edit\n/);
});

test("runVendor: missing source file warns but vendors the other items", async (t) => {
  const { home, repoRoot } = await tmpDirs();
  t.after(() => Promise.all([rm(home, { recursive: true, force: true }), rm(repoRoot, { recursive: true, force: true })]));

  // Only one of the two declared items exists on disk.
  await seedSuperpowers(home, { "ok/SKILL.md": "---\nname: ok\n---\n\nOK body.\n" });
  await mkdir(join(repoRoot, "catalog"), { recursive: true });

  const manifest = { sources: [
    { id: "superpowers", kind: "local", repo: "obra/superpowers", license: "MIT", items: [
      { from: "gone/SKILL.md", id: "sp-gone", roles: ["brainstorm"] },
      { from: "ok/SKILL.md", id: "sp-ok", roles: ["brainstorm"] }
    ] }
  ]};
  const res = await runVendor({ home, repoRoot, manifest });

  assert.equal(res.count, 1, "only the existing item is vendored");
  assert.ok(res.warnings.some(w => /missing item gone\/SKILL\.md/.test(w)), "expected missing-item warning");
  // The vendored item's SKILL.md was written.
  const written = await readFile(join(repoRoot, "plugin/builtins/sp-ok/SKILL.md"), "utf8");
  assert.match(written, /OK body\./);
  // NOTICE was written (>=1 entry) and carries the banner.
  const notice = await readFile(join(repoRoot, "NOTICE"), "utf8");
  assert.match(notice, /^GENERATED by `muster vendor` from vendor\/manifest\.yaml — do not edit/);
});
