import { test } from "node:test";
import assert from "node:assert/strict";
import { validateVendorManifest, toBuiltin, toAgent, generateNotice, runVendor, pickLatestVersion, splitFrontmatter, cloneCommandsFor } from "../src/vendor.js";
import { modelForRole } from "../src/model.js";
import { mkdtemp, mkdir, writeFile, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

// Ensure MUSTER_MAX_TIER never leaks in from the caller's environment and
// silently makes tier-policy assertions wrong. Mirror agents.muster.test.js.
delete process.env.MUSTER_MAX_TIER;

test("validateVendorManifest accepts a well-formed manifest", () => {
  const doc = { sources: [
    { id: "superpowers", kind: "local", repo: "obra/superpowers", license: "MIT",
      items: [{ from: "brainstorming/SKILL.md", id: "sp-brainstorm", roles: ["brainstorm"] }] }
  ]};
  assert.deepEqual(validateVendorManifest(doc), { ok: true, errors: [] });
});

test("validateVendorManifest rejects missing license / bad kind / itemless", () => {
  const doc = { sources: [{ id: "x", kind: "ftp", items: "no" }] };
  const r = validateVendorManifest(doc);
  assert.equal(r.ok, false);
  assert.ok(r.errors.some(e => /license/.test(e)));
  assert.ok(r.errors.some(e => /kind/.test(e)));
  assert.ok(r.errors.some(e => /items/.test(e)));
});

test("validateVendorManifest rejects item missing from/id/roles", () => {
  const doc = { sources: [{ id: "s", kind: "local", license: "MIT", items: [{ id: "only" }] }] };
  const r = validateVendorManifest(doc);
  assert.equal(r.ok, false);
  assert.ok(r.errors.some(e => /from/.test(e)));
  assert.ok(r.errors.some(e => /roles/.test(e)));
});

const src = `---\nname: brainstorming\ndescription: Explore before building\n---\n\n# Brainstorming\nDo the thing.\n`;
const item = { from: "brainstorming/SKILL.md", id: "sp-brainstorm", roles: ["brainstorm"] };
const source = { repo: "obra/superpowers", license: "MIT" };

test("toBuiltin merges provenance frontmatter, preserves body", () => {
  const r = toBuiltin(src, item, source);
  assert.equal(r.path, "plugin/builtins/sp-brainstorm/SKILL.md");
  assert.match(r.content, /muster_builtin: true/);
  assert.match(r.content, /adapted_from: obra\/superpowers brainstorming\/SKILL.md/);
  assert.match(r.content, /license: MIT/);
  assert.match(r.content, /name: brainstorming/);
  assert.match(r.content, /Do the thing\./);
});

test("toBuiltin emits a valid catalog builtin entry", () => {
  const r = toBuiltin(src, item, source);
  assert.deepEqual(r.catalogEntry, {
    id: "sp-brainstorm", kind: "builtin", roles: ["brainstorm"], rank: 50,
    provenance: { adapted_from: "obra/superpowers brainstorming/SKILL.md", license: "MIT" }
  });
});

test("toBuiltin derives name/description when source has no frontmatter", () => {
  const r = toBuiltin("# Bare\nbody", { from: "x.md", id: "wsh-x", roles: ["implement"] }, source);
  assert.match(r.content, /name: wsh-x/);
  assert.match(r.content, /body/);
});

test("toBuiltin is idempotent", () => {
  assert.equal(toBuiltin(src, item, source).content, toBuiltin(src, item, source).content);
});

test("toBuiltin keeps adapted_from on one line (no yaml wrapping)", () => {
  const longItem = { from: "plugins/some-very-long-marketplace-path/agents/extremely-long-agent-name.md", id: "wsh-x", roles: ["implement"] };
  const r = toBuiltin("# x\nbody", longItem, { repo: "wshobson/agents", license: "MIT" });
  const line = r.content.split("\n").find(l => l.startsWith("adapted_from:"));
  assert.ok(line.includes("extremely-long-agent-name.md"), "adapted_from must be on a single unwrapped line");
});

test("generateNotice lists each source repo + license once", () => {
  const entries = [
    { provenance: { adapted_from: "obra/superpowers a/SKILL.md", license: "MIT" } },
    { provenance: { adapted_from: "obra/superpowers b/SKILL.md", license: "MIT" } },
    { provenance: { adapted_from: "wshobson/agents x.md", license: "MIT" } }
  ];
  const n = generateNotice(entries);
  assert.match(n, /obra\/superpowers \(MIT\)/);
  assert.match(n, /wshobson\/agents \(MIT\)/);
  assert.equal((n.match(/obra\/superpowers/g) || []).length, 1);
});

test("generateNotice leads with the do-not-edit banner", () => {
  const n = generateNotice([{ provenance: { adapted_from: "obra/superpowers a/SKILL.md", license: "MIT" } }]);
  assert.match(n, /^GENERATED by `muster vendor` from vendor\/manifest\.yaml — do not edit/);
});

// --- runVendor: data-loss guards + banner -------------------------------------
// runVendor only fetches a local source's root for id "superpowers", reading from
// <home>/.claude/plugins/cache/claude-plugins-official/superpowers/<ver>/skills.
// We fabricate that tree so items vendor without a real git clone; any other local
// source id yields root:null, exercising the fetch-failure/empty path.

const SP_BASE = ".claude/plugins/cache/claude-plugins-official/superpowers";

// Seed a fake superpowers skills cache under `home`; `files` maps a relative path
// (the item's `from`) to its source text. Returns nothing.
async function seedSuperpowers(home, files) {
  const skills = join(home, SP_BASE, "v1.0.0", "skills");
  for (const [rel, text] of Object.entries(files)) {
    const abs = join(skills, rel);
    await mkdir(join(abs, ".."), { recursive: true });
    await writeFile(abs, text);
  }
}

async function tmpDirs() {
  const home = await mkdtemp(join(tmpdir(), "muster-vh-"));
  const repoRoot = await mkdtemp(join(tmpdir(), "muster-vr-"));
  return { home, repoRoot };
}

test("runVendor: all sources empty -> count 0, refuse-to-overwrite warning, artifacts untouched", async (t) => {
  const { home, repoRoot } = await tmpDirs();
  t.after(() => Promise.all([rm(home, { recursive: true, force: true }), rm(repoRoot, { recursive: true, force: true })]));

  // Pre-seed existing generated artifacts that must NOT be clobbered.
  await mkdir(join(repoRoot, "catalog"), { recursive: true });
  const sentinel = "- id: pre-existing\n";
  await writeFile(join(repoRoot, "catalog/builtins.generated.yaml"), sentinel);
  await writeFile(join(repoRoot, "catalog/agents.generated.yaml"), sentinel);
  await writeFile(join(repoRoot, "NOTICE"), "PRE-EXISTING NOTICE\n");

  // A local source whose id != superpowers always yields root:null.
  const manifest = { sources: [
    { id: "nope", kind: "local", repo: "x/y", license: "MIT",
      items: [{ from: "a/SKILL.md", id: "a", roles: ["brainstorm"] }] }
  ]};
  const res = await runVendor({ home, repoRoot, manifest });

  assert.equal(res.count, 0);
  assert.ok(res.warnings.some(w => /refusing to overwrite/.test(w)), "expected refuse-to-overwrite warning");
  assert.ok(res.warnings.some(w => /could not fetch/.test(w)), "expected fetch-failure warning");
  // Artifacts unchanged.
  assert.equal(await readFile(join(repoRoot, "catalog/builtins.generated.yaml"), "utf8"), sentinel);
  assert.equal(await readFile(join(repoRoot, "catalog/agents.generated.yaml"), "utf8"), sentinel);
  assert.equal(await readFile(join(repoRoot, "NOTICE"), "utf8"), "PRE-EXISTING NOTICE\n");
});

test("runVendor: agent-only vendor does not rewrite builtins.generated.yaml", async (t) => {
  const { home, repoRoot } = await tmpDirs();
  t.after(() => Promise.all([rm(home, { recursive: true, force: true }), rm(repoRoot, { recursive: true, force: true })]));

  await seedSuperpowers(home, { "ag/AGENT.md": "---\nname: rev\n---\n\nReview body.\n" });
  await mkdir(join(repoRoot, "catalog"), { recursive: true });
  const builtinSentinel = "- id: keep-me\n";
  await writeFile(join(repoRoot, "catalog/builtins.generated.yaml"), builtinSentinel);

  const manifest = { sources: [
    { id: "superpowers", kind: "local", repo: "obra/superpowers", license: "MIT",
      items: [{ from: "ag/AGENT.md", id: "sp-rev", roles: ["architecture-review"], as: "agent" }] }
  ]};
  const res = await runVendor({ home, repoRoot, manifest });

  assert.equal(res.count, 1);
  assert.equal(res.agents, 1);
  assert.equal(res.builtins, 0);
  // builtins catalog untouched (no builtin entries produced).
  assert.equal(await readFile(join(repoRoot, "catalog/builtins.generated.yaml"), "utf8"), builtinSentinel);
  // agents catalog written with the do-not-edit banner.
  const agents = await readFile(join(repoRoot, "catalog/agents.generated.yaml"), "utf8");
  assert.match(agents, /^# GENERATED by `muster vendor` from vendor\/manifest\.yaml — do not edit\n/);
  assert.match(agents, /id: sp-rev/);
});

test("runVendor: builtin-only vendor does not rewrite agents.generated.yaml", async (t) => {
  const { home, repoRoot } = await tmpDirs();
  t.after(() => Promise.all([rm(home, { recursive: true, force: true }), rm(repoRoot, { recursive: true, force: true })]));

  await seedSuperpowers(home, { "bs/SKILL.md": "---\nname: brainstorm\n---\n\nBrainstorm body.\n" });
  await mkdir(join(repoRoot, "catalog"), { recursive: true });
  const agentSentinel = "- id: keep-agent\n";
  await writeFile(join(repoRoot, "catalog/agents.generated.yaml"), agentSentinel);

  const manifest = { sources: [
    { id: "superpowers", kind: "local", repo: "obra/superpowers", license: "MIT",
      items: [{ from: "bs/SKILL.md", id: "sp-bs", roles: ["brainstorm"] }] }
  ]};
  const res = await runVendor({ home, repoRoot, manifest });

  assert.equal(res.builtins, 1);
  assert.equal(res.agents, 0);
  assert.equal(await readFile(join(repoRoot, "catalog/agents.generated.yaml"), "utf8"), agentSentinel);
  const builtins = await readFile(join(repoRoot, "catalog/builtins.generated.yaml"), "utf8");
  assert.match(builtins, /^# GENERATED by `muster vendor` from vendor\/manifest\.yaml — do not edit\n/);
});

test("runVendor: missing source file warns but vendors the other items", async (t) => {
  const { home, repoRoot } = await tmpDirs();
  t.after(() => Promise.all([rm(home, { recursive: true, force: true }), rm(repoRoot, { recursive: true, force: true })]));

  // Only one of the two declared items exists on disk.
  await seedSuperpowers(home, { "ok/SKILL.md": "---\nname: ok\n---\n\nOK body.\n" });
  await mkdir(join(repoRoot, "catalog"), { recursive: true });

  const manifest = { sources: [
    { id: "superpowers", kind: "local", repo: "obra/superpowers", license: "MIT", items: [
      { from: "gone/SKILL.md", id: "sp-gone", roles: ["brainstorm"] },
      { from: "ok/SKILL.md", id: "sp-ok", roles: ["brainstorm"] }
    ] }
  ]};
  const res = await runVendor({ home, repoRoot, manifest });

  assert.equal(res.count, 1, "only the existing item is vendored");
  assert.ok(res.warnings.some(w => /missing item gone\/SKILL\.md/.test(w)), "expected missing-item warning");
  // The vendored item's SKILL.md was written.
  const written = await readFile(join(repoRoot, "plugin/builtins/sp-ok/SKILL.md"), "utf8");
  assert.match(written, /OK body\./);
  // NOTICE was written (>=1 entry) and carries the banner.
  const notice = await readFile(join(repoRoot, "NOTICE"), "utf8");
  assert.match(notice, /^GENERATED by `muster vendor` from vendor\/manifest\.yaml — do not edit/);
});

// --- pickLatestVersion --------------------------------------------------------

test("pickLatestVersion: semver beats content-hash (5.1.0, 10.0.0, hash)", () => {
  assert.equal(pickLatestVersion(["5.1.0", "10.0.0", "6fd450765978"]), "10.0.0");
});

test("pickLatestVersion: numeric major comparison (9.1.0 vs 10.0.0)", () => {
  assert.equal(pickLatestVersion(["9.1.0", "10.0.0"]), "10.0.0");
});

test("pickLatestVersion: minor comparison", () => {
  assert.equal(pickLatestVersion(["2.9.0", "2.10.0", "2.1.0"]), "2.10.0");
});

test("pickLatestVersion: patch comparison", () => {
  assert.equal(pickLatestVersion(["1.0.9", "1.0.10", "1.0.2"]), "1.0.10");
});

test("pickLatestVersion: all hashes falls back to first entry", () => {
  assert.equal(pickLatestVersion(["6fd450765978", "abc123"]), "6fd450765978");
});

test("pickLatestVersion: empty list returns undefined", () => {
  assert.equal(pickLatestVersion([]), undefined);
});

test("pickLatestVersion: single semver entry", () => {
  assert.equal(pickLatestVersion(["3.2.1"]), "3.2.1");
});

// --- toAgent: model resolution ------------------------------------------------

const agentSrc = `---\nname: my-agent\ndescription: Does the thing\n---\n\n# My Agent\nBody text.\n`;
const agentSource = { repo: "obra/superpowers", license: "MIT" };

test("toAgent model passthrough: explicit item.model wins verbatim", () => {
  const item = { from: "ag/AGENT.md", id: "sp-ag", roles: ["architecture-review"], model: "haiku" };
  const r = toAgent(agentSrc, item, agentSource);
  const { data } = splitFrontmatter(r.content);
  assert.equal(data.model, "haiku");
});

test("toAgent architecture-review role → modelForRole policy (fable→opus by default)", () => {
  const item = { from: "ag/AGENT.md", id: "sp-arch", roles: ["architecture-review"] };
  const r = toAgent(agentSrc, item, agentSource);
  const { data } = splitFrontmatter(r.content);
  // Expectation derived from policy, not hardcoded — follows modelForRole.
  assert.equal(data.model, modelForRole("architecture-review"));
});

test("toAgent default roles (implement) → sonnet", () => {
  const item = { from: "ag/AGENT.md", id: "sp-impl", roles: ["implement"] };
  const r = toAgent(agentSrc, item, agentSource);
  const { data } = splitFrontmatter(r.content);
  assert.equal(data.model, "sonnet");
});

test("toAgent haiku-tier roles only → sonnet floor applies (not haiku)", () => {
  // "research" maps to haiku in modelForRole but toAgent floors at sonnet.
  const item = { from: "ag/AGENT.md", id: "sp-research", roles: ["research"] };
  const r = toAgent(agentSrc, item, agentSource);
  const { data } = splitFrontmatter(r.content);
  assert.equal(data.model, "sonnet");
  assert.notEqual(data.model, "haiku");
});

test("toAgent frontmatter carries resolved model field", () => {
  const item = { from: "ag/AGENT.md", id: "sp-carry", roles: ["implement"] };
  const r = toAgent(agentSrc, item, agentSource);
  // Verify the raw content string contains a model key, and that parsing it
  // round-trips to the same value — exercises splitFrontmatter integration.
  assert.match(r.content, /^model:/m);
  const { data } = splitFrontmatter(r.content);
  assert.ok(data.model, "frontmatter must have a non-empty model field");
  assert.equal(data.model, "sonnet");
});

test("runVendor: resolveSuperpowers picks highest semver dir over content-hash dir", async (t) => {
  const { home, repoRoot } = await tmpDirs();
  t.after(() => Promise.all([rm(home, { recursive: true, force: true }), rm(repoRoot, { recursive: true, force: true })]));

  // Plant a skills dir under BOTH a semver version and a hash dir.
  // The hash dir lexicographically sorts after "5.1.0" but before "10.0.0",
  // so the old sort().reverse() would have returned the hash dir.
  const base = join(home, SP_BASE);
  const hashDir = join(base, "6fd450765978", "skills");
  const oldSemverDir = join(base, "5.1.0", "skills");
  const newSemverDir = join(base, "10.0.0", "skills");
  for (const dir of [hashDir, oldSemverDir, newSemverDir]) {
    await mkdir(dir, { recursive: true });
    await writeFile(join(dir, "SKILL.md"), "---\nname: test\n---\n\nBody.\n");
  }
  await mkdir(join(repoRoot, "catalog"), { recursive: true });

  const manifest = { sources: [
    { id: "superpowers", kind: "local", repo: "obra/superpowers", license: "MIT",
      items: [{ from: "SKILL.md", id: "sp-test", roles: ["brainstorm"] }] }
  ]};
  const res = await runVendor({ home, repoRoot, manifest });

  // Should succeed (picked 10.0.0, not the hash dir or 5.1.0).
  assert.equal(res.count, 1);
  assert.equal(res.warnings.filter(w => /could not fetch/.test(w)).length, 0);
});

// --- item.description override in toBuiltin / toAgent -------------------------

test("toBuiltin: item.description overrides data.description and fallback", () => {
  // Source has its own frontmatter description, but item pins a different one.
  const srcWithDesc = `---\nname: verify\ndescription: Source-level description\n---\n\nBody.\n`;
  const itemWithDesc = { from: "verify/SKILL.md", id: "gsd-verify-work", roles: ["plan"], description: "Built-in for verify — UAT + gap-closure verification of completed work" };
  const r = toBuiltin(srcWithDesc, itemWithDesc, source);
  const { data } = splitFrontmatter(r.content);
  assert.equal(data.description, "Built-in for verify — UAT + gap-closure verification of completed work");
});

test("toBuiltin: item.description beats fallback when source has no description", () => {
  const srcNoDesc = `---\nname: verify\n---\n\nBody.\n`;
  const itemWithDesc = { from: "verify/SKILL.md", id: "gsd-verify-work", roles: ["plan"], description: "Custom description" };
  const r = toBuiltin(srcNoDesc, itemWithDesc, source);
  const { data } = splitFrontmatter(r.content);
  assert.equal(data.description, "Custom description");
});

test("toBuiltin: item.description propagates into catalogEntry when set", () => {
  const srcWithDesc = `---\nname: x\ndescription: source-desc\n---\n\nBody.\n`;
  const itemWithDesc = { from: "x/SKILL.md", id: "x", roles: ["plan"], description: "override-desc" };
  const r = toBuiltin(srcWithDesc, itemWithDesc, source);
  assert.equal(r.catalogEntry.description, "override-desc");
});

test("toBuiltin: catalogEntry description absent when item has no description override", () => {
  // When no item.description is set, catalogEntry should have no description field.
  const srcWithDesc = `---\nname: x\ndescription: d\n---\n\nBody.\n`;
  const itemPlain = { from: "x/SKILL.md", id: "x", roles: ["plan"] };
  const r = toBuiltin(srcWithDesc, itemPlain, source);
  assert.equal(r.catalogEntry.description, undefined);
});

test("toBuiltin: item.rank overrides default 50 in catalogEntry", () => {
  const r = toBuiltin(src, { ...item, rank: 48 }, source);
  assert.equal(r.catalogEntry.rank, 48);
});

test("toBuiltin: catalogEntry rank defaults to 50 when item has no rank", () => {
  const r = toBuiltin(src, item, source);
  assert.equal(r.catalogEntry.rank, 50);
});

// --- no two builtin catalog entries share an identical description ---------------
// This catches future accidental duplicate descriptions like gsd-plan-phase vs gsd-verify-work.
import { sep } from "node:path";
import { readFile as readFileFn } from "node:fs/promises";
import { parse as parseFn } from "yaml";

// --- Security: source.id path-traversal rejection ---

test("validateVendorManifest rejects source.id with path-traversal characters", () => {
  const doc = { sources: [
    { id: "../../../etc", kind: "local", license: "MIT", items: [{ from: "f.md", id: "ok", roles: ["brainstorm"] }] }
  ]};
  const r = validateVendorManifest(doc);
  assert.equal(r.ok, false);
  assert.ok(r.errors.some(e => /sources\[0\]\.id/.test(e) && /invalid/.test(e)), `expected id-invalid error, got: ${JSON.stringify(r.errors)}`);
});

test("validateVendorManifest rejects source.id with slash", () => {
  const doc = { sources: [
    { id: "a/b", kind: "local", license: "MIT", items: [{ from: "f.md", id: "ok", roles: ["brainstorm"] }] }
  ]};
  const r = validateVendorManifest(doc);
  assert.equal(r.ok, false);
  assert.ok(r.errors.some(e => /sources\[0\]\.id/.test(e) && /invalid/.test(e)));
});

test("validateVendorManifest accepts source.id with allowed chars (alphanumeric, dash, underscore)", () => {
  const doc = { sources: [
    { id: "my-source_01", kind: "local", license: "MIT", items: [{ from: "f.md", id: "ok", roles: ["brainstorm"] }] }
  ]};
  const r = validateVendorManifest(doc);
  // Only fails if something else is wrong (no id-invalid error)
  assert.ok(!r.errors.some(e => /id.*invalid/.test(e)));
});

// --- Security: item.from traversal warn+skip in runVendor ---

test("runVendor: item.from traversal path is warned and skipped", async (t) => {
  const { home, repoRoot } = await tmpDirs();
  t.after(() => Promise.all([rm(home, { recursive: true, force: true }), rm(repoRoot, { recursive: true, force: true })]));

  // Seed a real file at a location outside the expected root (simulated via a separate tmp dir)
  // We seed the superpowers root normally but provide a traversal item.from.
  await seedSuperpowers(home, { "ok/SKILL.md": "---\nname: ok\n---\n\nBody.\n" });
  await mkdir(join(repoRoot, "catalog"), { recursive: true });

  // Plant a file that would be accessible via traversal at the skills root's parent
  const skillsRoot = join(home, SP_BASE, "v1.0.0", "skills");
  // Write a sentinel file one level above skills root
  const outsideFile = join(skillsRoot, "..", "outside.md");
  await writeFile(outsideFile, "---\nname: outside\n---\n\nSECRET.\n");

  const manifest = { sources: [
    { id: "superpowers", kind: "local", repo: "obra/superpowers", license: "MIT", items: [
      { from: "../outside.md", id: "sp-traversal", roles: ["brainstorm"] },
      { from: "ok/SKILL.md", id: "sp-ok", roles: ["brainstorm"] }
    ]}
  ]};
  const res = await runVendor({ home, repoRoot, manifest });

  // The traversal item is skipped with a warning; the valid item still vendors.
  assert.equal(res.count, 1, "only the safe item should be vendored");
  assert.ok(res.warnings.some(w => /traversal/.test(w) || /outside of source root/.test(w)),
    `expected traversal warning, got: ${JSON.stringify(res.warnings)}`);
  // The traversal item must NOT have been written.
  const traversalPath = join(repoRoot, "plugin/builtins/sp-traversal/SKILL.md");
  const traversalExists = await import("../src/fs-util.js").then(m => m.exists(traversalPath));
  assert.equal(traversalExists, false, "traversal item must not be written");
});

// --- Security: item.id path-traversal rejection ---

test("validateVendorManifest rejects item.id with path-traversal characters", () => {
  const doc = { sources: [
    { id: "s", kind: "local", license: "MIT", items: [
      { from: "f.md", id: "../../.claude/x", roles: ["brainstorm"] }
    ]}
  ]};
  const r = validateVendorManifest(doc);
  assert.equal(r.ok, false);
  assert.ok(r.errors.some(e => /items\[0\]\.id/.test(e) && /invalid/.test(e)), `expected item id-invalid error, got: ${JSON.stringify(r.errors)}`);
});

test("validateVendorManifest rejects item.id with dot prefix", () => {
  const doc = { sources: [
    { id: "s", kind: "local", license: "MIT", items: [
      { from: "f.md", id: ".hidden", roles: ["brainstorm"] }
    ]}
  ]};
  const r = validateVendorManifest(doc);
  assert.equal(r.ok, false);
  assert.ok(r.errors.some(e => /items\[0\]\.id/.test(e) && /invalid/.test(e)));
});

// --- Security: source.repo format validation ---

test("validateVendorManifest rejects source.repo with extra path components", () => {
  const doc = { sources: [
    { id: "s", kind: "github", license: "MIT", repo: "owner/repo/extra",
      items: [{ from: "f.md", id: "ok", roles: ["brainstorm"] }] }
  ]};
  const r = validateVendorManifest(doc);
  assert.equal(r.ok, false);
  assert.ok(r.errors.some(e => /repo/.test(e) && /invalid/.test(e)), `expected repo-invalid error, got: ${JSON.stringify(r.errors)}`);
});

test("validateVendorManifest rejects source.repo without slash (bare name)", () => {
  const doc = { sources: [
    { id: "s", kind: "github", license: "MIT", repo: "justname",
      items: [{ from: "f.md", id: "ok", roles: ["brainstorm"] }] }
  ]};
  const r = validateVendorManifest(doc);
  assert.equal(r.ok, false);
  assert.ok(r.errors.some(e => /repo/.test(e) && /invalid/.test(e)));
});

test("validateVendorManifest accepts valid owner/name repo", () => {
  const doc = { sources: [
    { id: "s", kind: "github", license: "MIT", repo: "my-org/my.repo_01",
      items: [{ from: "f.md", id: "ok", roles: ["brainstorm"] }] }
  ]};
  const r = validateVendorManifest(doc);
  assert.ok(!r.errors.some(e => /repo.*invalid/.test(e)));
});

// --- Security: source.ref validation ---

test("validateVendorManifest rejects source.ref starting with dash (git flag injection)", () => {
  const doc = { sources: [
    { id: "s", kind: "github", license: "MIT", repo: "owner/repo", ref: "--upload-pack=malicious",
      items: [{ from: "f.md", id: "ok", roles: ["brainstorm"] }] }
  ]};
  const r = validateVendorManifest(doc);
  assert.equal(r.ok, false);
  assert.ok(r.errors.some(e => /ref/.test(e) && /invalid/.test(e)), `expected ref-invalid error, got: ${JSON.stringify(r.errors)}`);
});

test("validateVendorManifest rejects source.ref with disallowed characters (space, semicolon)", () => {
  const doc = { sources: [
    { id: "s", kind: "github", license: "MIT", repo: "owner/repo", ref: "main; rm -rf /",
      items: [{ from: "f.md", id: "ok", roles: ["brainstorm"] }] }
  ]};
  const r = validateVendorManifest(doc);
  assert.equal(r.ok, false);
  assert.ok(r.errors.some(e => /ref/.test(e) && /invalid/.test(e)));
});

test("validateVendorManifest accepts valid ref strings (branch, tag, semver)", () => {
  for (const ref of ["main", "v1.0.0", "feature/my-branch", "refs/heads/main"]) {
    const doc = { sources: [
      { id: "s", kind: "github", license: "MIT", repo: "owner/repo", ref,
        items: [{ from: "f.md", id: "ok", roles: ["brainstorm"] }] }
    ]};
    const r = validateVendorManifest(doc);
    assert.ok(!r.errors.some(e => /ref.*invalid/.test(e)), `ref "${ref}" should be accepted, errors: ${JSON.stringify(r.errors)}`);
  }
});

// --- Security: tools allowlist filtering in toAgent ---

test("toAgent filters unknown tools from frontmatter, keeping only ALLOWED_TOOLS", () => {
  const srcWithBadTools = `---\nname: my-agent\ntools: Read, Bash, EvalCode, RunShell\n---\n\nBody.\n`;
  const it = { from: "ag/AGENT.md", id: "sp-ag", roles: ["implement"] };
  const r = toAgent(srcWithBadTools, it, agentSource);
  const { data } = splitFrontmatter(r.content);
  const tools = data.tools.split(",").map(s => s.trim());
  assert.ok(tools.includes("Read"), "Read should be allowed through");
  assert.ok(tools.includes("Bash"), "Bash should be allowed through");
  assert.ok(!tools.includes("EvalCode"), "EvalCode must be filtered out");
  assert.ok(!tools.includes("RunShell"), "RunShell must be filtered out");
});

test("toAgent falls back to default tools string when all frontmatter tools are disallowed", () => {
  const srcAllBad = `---\nname: my-agent\ntools: EvalCode, RunShell, ExecArbitrary\n---\n\nBody.\n`;
  const it = { from: "ag/AGENT.md", id: "sp-ag2", roles: ["implement"] };
  const r = toAgent(srcAllBad, it, agentSource);
  const { data } = splitFrontmatter(r.content);
  // Must fall back to a non-empty default string containing at least Read
  assert.ok(typeof data.tools === "string" && data.tools.length > 0, "tools must be non-empty");
  assert.ok(data.tools.includes("Read"), "fallback must include Read");
});

test("toAgent passes through all-allowed tools unchanged", () => {
  const srcGoodTools = `---\nname: my-agent\ntools: Read, Grep, Glob\n---\n\nBody.\n`;
  const it = { from: "ag/AGENT.md", id: "sp-ag3", roles: ["implement"] };
  const r = toAgent(srcGoodTools, it, agentSource);
  const { data } = splitFrontmatter(r.content);
  const tools = data.tools.split(",").map(s => s.trim());
  assert.deepEqual(tools, ["Read", "Grep", "Glob"]);
});

// --- Security: shipped builtin catalog entries all have unique descriptions ---

test("shipped builtin catalog entries all have unique descriptions (no duplicates)", async () => {
  const raw = await readFileFn(new URL("../catalog/builtins.generated.yaml", import.meta.url), "utf8");
  const entries = parseFn(raw);
  assert.ok(Array.isArray(entries), "catalog must be an array");
  // Only entries that have a description field are subject to the uniqueness check.
  const withDesc = entries.filter(e => typeof e.description === "string" && e.description.length > 0);
  const seen = new Map();
  for (const e of withDesc) {
    if (seen.has(e.description)) {
      assert.fail(`Duplicate description "${e.description}" on entries "${seen.get(e.description)}" and "${e.id}"`);
    }
    seen.set(e.description, e.id);
  }
});

// --- cloneCommandsFor: SHA vs branch dispatch ----------------------------------

const SHA = "cf6059d030bf4fe96623ae2e596d2f31e35fedc0";
const SHA2 = "85cfa5dc136200667e3044ef2827747880314e03";
const shaSource = { kind: "github", repo: "wshobson/agents", ref: SHA };
const branchSource = { kind: "github", repo: "wshobson/agents", ref: "main" };
const tagSource = { kind: "github", repo: "wshobson/agents", ref: "v1.2.3" };

test("cloneCommandsFor: SHA ref produces init+remote-add+fetch+checkout sequence", () => {
  const cmds = cloneCommandsFor(shaSource, "/tmp/test-dir");
  // Must return an array of [cmd, argv] pairs
  assert.ok(Array.isArray(cmds), "cloneCommandsFor must return an array");
  assert.equal(cmds.length, 4, "SHA path must produce exactly 4 git operations");
  // First: git init <dir>
  assert.deepEqual(cmds[0], ["git", ["init", "/tmp/test-dir"]]);
  // Second: git -C <dir> remote add origin <url>
  assert.deepEqual(cmds[1], ["git", ["-C", "/tmp/test-dir", "remote", "add", "origin", "https://github.com/wshobson/agents.git"]]);
  // Third: git -C <dir> fetch --depth 1 origin <sha>
  assert.deepEqual(cmds[2], ["git", ["-C", "/tmp/test-dir", "fetch", "--depth", "1", "origin", SHA]]);
  // Fourth: git -C <dir> checkout FETCH_HEAD
  assert.deepEqual(cmds[3], ["git", ["-C", "/tmp/test-dir", "checkout", "FETCH_HEAD"]]);
});

test("cloneCommandsFor: branch ref produces single clone command", () => {
  const cmds = cloneCommandsFor(branchSource, "/tmp/test-dir");
  assert.ok(Array.isArray(cmds), "cloneCommandsFor must return an array");
  assert.equal(cmds.length, 1, "branch path must produce exactly 1 git operation");
  assert.deepEqual(cmds[0], ["git", ["clone", "--depth", "1", "--branch", "main",
    "https://github.com/wshobson/agents.git", "/tmp/test-dir"]]);
});

test("cloneCommandsFor: tag ref produces single clone command", () => {
  const cmds = cloneCommandsFor(tagSource, "/tmp/test-dir");
  assert.equal(cmds.length, 1, "tag path must produce exactly 1 git operation");
  assert.deepEqual(cmds[0], ["git", ["clone", "--depth", "1", "--branch", "v1.2.3",
    "https://github.com/wshobson/agents.git", "/tmp/test-dir"]]);
});

test("cloneCommandsFor: lowercase 40-hex SHA is dispatched as SHA path", () => {
  const src = { kind: "github", repo: "open-gsd/gsd-core", ref: SHA2 };
  const cmds = cloneCommandsFor(src, "/tmp/gsd-dir");
  assert.equal(cmds.length, 4, "40-hex lowercase SHA must use SHA fetch path");
  assert.ok(cmds[2][1].includes(SHA2), "fetch must include the exact SHA");
});

test("cloneCommandsFor: uppercase 40-hex SHA is dispatched as SHA path", () => {
  const src = { kind: "github", repo: "owner/repo", ref: SHA.toUpperCase() };
  const cmds = cloneCommandsFor(src, "/tmp/upper-dir");
  assert.equal(cmds.length, 4, "uppercase 40-hex SHA must use SHA fetch path");
});

test("cloneCommandsFor: 39-hex string (not SHA length) uses clone path", () => {
  const notAFullSha = "cf6059d030bf4fe96623ae2e596d2f31e35fedc";  // 39 chars
  const src = { kind: "github", repo: "owner/repo", ref: notAFullSha };
  const cmds = cloneCommandsFor(src, "/tmp/dir");
  assert.equal(cmds.length, 1, "39-hex must fall through to clone path");
});

test("cloneCommandsFor: missing ref defaults to main via clone path", () => {
  const src = { kind: "github", repo: "owner/repo" };
  const cmds = cloneCommandsFor(src, "/tmp/dir");
  assert.equal(cmds.length, 1, "missing ref must use clone path with main");
  assert.ok(cmds[0][1].includes("main"), "must default branch to main");
});

// --- validateVendorManifest: 40-hex SHA ref accepted --------------------------

test("validateVendorManifest accepts 40-hex SHA as a valid ref", () => {
  const doc = { sources: [
    { id: "s", kind: "github", license: "MIT", repo: "owner/repo", ref: SHA,
      items: [{ from: "f.md", id: "ok", roles: ["brainstorm"] }] }
  ]};
  const r = validateVendorManifest(doc);
  assert.ok(!r.errors.some(e => /ref.*invalid/.test(e)),
    `40-hex SHA should be accepted, errors: ${JSON.stringify(r.errors)}`);
});

// --- real vendor/manifest.yaml validates with pinned SHAs --------------------

test("vendor/manifest.yaml with pinned SHAs validates cleanly", async () => {
  const { parse: parseYaml } = await import("yaml");
  const { readFile: rf } = await import("node:fs/promises");
  const raw = await rf(new URL("../vendor/manifest.yaml", import.meta.url), "utf8");
  const doc = parseYaml(raw);
  const r = validateVendorManifest(doc);
  assert.deepEqual(r, { ok: true, errors: [] }, `manifest should validate, errors: ${JSON.stringify(r.errors)}`);
});

// --- runVendor: local bare-git fixture via source.url seam --------------------
//
// The seam: cloneCommandsFor accepts source.url as an optional override so tests
// can point a github-kind source at a local bare repo without network access.
// When source.url is absent the function is byte-identical to the original
// (it builds the https://github.com/<repo>.git URL as before).
//
// This fixture:
//   1. Creates a bare git repo (the "remote").
//   2. Clones it into a work dir, writes a SKILL.md with known content, commits,
//      and pushes back to the bare repo so the branch ref is present.
//   3. Captures the commit SHA so we can test both the branch-clone path and
//      the SHA-fetch path.

const { promisify: prom } = await import("node:util");
const { execFile: ef } = await import("node:child_process");
const pex = prom(ef);

async function createLocalBareFixture(base) {
  const bare = join(base, "bare.git");
  const work = join(base, "work");
  const skillContent = "---\nname: local-fixture\ndescription: Fixture skill for vendor integration test\n---\n\n# Local Fixture\nBody text.\n";

  // git init --bare
  await pex("git", ["init", "--bare", bare]);
  // clone the bare repo
  await pex("git", ["clone", bare, work]);
  // configure identity (needed in some CI envs)
  await pex("git", ["-C", work, "config", "user.email", "test@test.local"]);
  await pex("git", ["-C", work, "config", "user.name", "Test"]);
  // write a skill file
  await mkdir(join(work, "skills", "fixture"), { recursive: true });
  await writeFile(join(work, "skills", "fixture", "SKILL.md"), skillContent);
  // stage, commit
  await pex("git", ["-C", work, "add", "."]);
  await pex("git", ["-C", work, "commit", "-m", "add fixture skill"]);
  // push to bare
  await pex("git", ["-C", work, "push", "origin", "HEAD:main"]);
  // capture SHA
  const { stdout: sha } = await pex("git", ["-C", work, "rev-parse", "HEAD"]);
  return { bare, work, sha: sha.trim(), skillContent };
}

test("runVendor: github-kind source via source.url (branch ref) vendors a local bare-git fixture", async (t) => {
  const base = await mkdtemp(join(tmpdir(), "muster-vgit-branch-"));
  const { home, repoRoot } = await tmpDirs();
  t.after(() => Promise.all([
    rm(base, { recursive: true, force: true }),
    rm(home, { recursive: true, force: true }),
    rm(repoRoot, { recursive: true, force: true })
  ]));

  const { bare } = await createLocalBareFixture(base);
  await mkdir(join(repoRoot, "catalog"), { recursive: true });

  // source.url overrides the github URL; source.repo is still required by
  // validateVendorManifest (owner/name format) but is not used for the clone.
  const manifest = { sources: [
    {
      id: "local-git-fixture",
      kind: "github",
      repo: "test/fixture",
      license: "MIT",
      ref: "main",
      url: bare,           // <-- seam: use the local bare repo path
      items: [{ from: "skills/fixture/SKILL.md", id: "fix-skill", roles: ["brainstorm"] }]
    }
  ]};

  const res = await runVendor({ home, repoRoot, manifest });

  assert.equal(res.count, 1, `expected 1 vendored item, got ${res.count}; warnings: ${JSON.stringify(res.warnings)}`);
  assert.equal(res.builtins, 1);
  const written = await readFile(join(repoRoot, "plugin/builtins/fix-skill/SKILL.md"), "utf8");
  assert.match(written, /Local Fixture/, "vendored SKILL.md must contain fixture body");
  assert.match(written, /muster_builtin: true/, "vendored SKILL.md must carry muster_builtin frontmatter");
});

test("runVendor: github-kind source via source.url (SHA ref) vendors a local bare-git fixture", async (t) => {
  const base = await mkdtemp(join(tmpdir(), "muster-vgit-sha-"));
  const { home, repoRoot } = await tmpDirs();
  t.after(() => Promise.all([
    rm(base, { recursive: true, force: true }),
    rm(home, { recursive: true, force: true }),
    rm(repoRoot, { recursive: true, force: true })
  ]));

  const { bare, sha } = await createLocalBareFixture(base);
  await mkdir(join(repoRoot, "catalog"), { recursive: true });

  // For the SHA path, cloneCommandsFor uses init + remote-add + fetch FETCH_HEAD.
  // The SHA init/fetch commands do not support --depth on a local bare repo in
  // all git versions, so we omit --depth by using the SHA ref path but via a
  // normal clone (branch-path); however we still validate the SHA path by
  // verifying that cloneCommandsFor picks the right sequence, and separately
  // exercise runVendor end-to-end with a branch ref (already done above).
  // To avoid the --depth limitation on local repos we use a full clone here
  // by setting ref to the SHA but falling back: the SHA_RE only matches a
  // 40-hex string, so we just use the real SHA from the fixture.
  assert.match(sha, /^[0-9a-f]{40}$/i, "SHA from fixture must be 40-hex");

  const manifest = { sources: [
    {
      id: "local-git-sha-fixture",
      kind: "github",
      repo: "test/fixture",
      license: "MIT",
      ref: sha,
      url: bare,           // seam: local bare repo
      items: [{ from: "skills/fixture/SKILL.md", id: "fix-skill-sha", roles: ["brainstorm"] }]
    }
  ]};

  const res = await runVendor({ home, repoRoot, manifest });

  // git fetch --depth 1 <sha> may fail on local repos in some git versions —
  // we accept either a successful vendor (1 item) or a graceful warning.
  // The important invariant is that runVendor does NOT throw and the result
  // shape is always valid.
  assert.ok(typeof res.count === "number", "result must have a numeric count");
  assert.ok(Array.isArray(res.warnings), "result must have a warnings array");

  if (res.count === 1) {
    const written = await readFile(join(repoRoot, "plugin/builtins/fix-skill-sha/SKILL.md"), "utf8");
    assert.match(written, /Local Fixture/, "vendored SKILL.md must contain fixture body");
  } else {
    // The SHA fetch didn't work on this git version/platform — that's acceptable.
    assert.ok(res.warnings.some(w => /local-git-sha-fixture/.test(w) || /could not fetch/.test(w)),
      `expected a fetch-failure warning; got: ${JSON.stringify(res.warnings)}`);
  }
});

test("cloneCommandsFor: source.url override replaces github URL", () => {
  const src = { kind: "github", repo: "owner/repo", ref: "main", url: "/tmp/local-bare.git" };
  const cmds = cloneCommandsFor(src, "/tmp/test-dir");
  assert.equal(cmds.length, 1, "branch path");
  // The URL in the clone command must be the override, not the github URL.
  assert.ok(cmds[0][1].includes("/tmp/local-bare.git"), "must use source.url override");
  assert.ok(!cmds[0][1].some(a => a.includes("github.com")), "must NOT include github.com");
});

test("cloneCommandsFor: source.url absent → default github URL (byte-identical to original)", () => {
  const src = { kind: "github", repo: "wshobson/agents", ref: "main" };
  const cmds = cloneCommandsFor(src, "/tmp/test-dir");
  assert.equal(cmds.length, 1);
  assert.ok(cmds[0][1].includes("https://github.com/wshobson/agents.git"),
    "must fall back to https://github.com URL when source.url is absent");
});
